language: node_js
node_js:
- '4.4'
- '5.11'
- '6.2'

script: npm run lint && npm test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf ./coverage

deploy:
  provider: npm
  email: accounts@acloud.guru
  api_key:
    secure: BFfRK5y1ulElx7aTiB5tNgDgIeFCJDW55pC8dNcfK8A+Ng+kZxu2BiWMwuy+Hmg2ElpNkmHznw2gfEL5enoQKdARUoIyfmj27D2nKUm1zoA48cvP35dTgomp0Rbpmq2nkGJ05xNTDeLjUfLIcv84shnO4jOxtVRP/VWENYJ1M9FibakhopUSsDtEh3XS2bwi0lU8FqS5VZVU2+2VZEapNQMGJNRqQzV8zyjcmrvzxbcazqSVi2urpQ6CFRU25a5snqp8OGIyd+jJfLXqpJofktlYvnHQDnkETEGskF9xMBt+k8//qIn+8zQk58SEFO8RhfInfs163c+cGJezucL1pd6BsRFZu4t11PEMSpGe9qFGMTmajZNuucV94rDcbwE8vdcJCFKU2NDyBhSCtp/Y1/Y39w6+T75os4HtkaMNtHy3UhJD5GM9Nm4dbwywm5toDlEhyVWIbSM1P3TTCFv0etKccCF3bJlB5rXOoynIUwhm8BKnjw1Su8vaV9RyNyUHyN+ZyejTAp3wYEJPuP1SYTsZXUXYxocTDxS/Y1aiVrwILWsFpSlRmmyX1S1C2yYZ2ExL/QolxeqRcL46cOr5pHZ+n/jLReh7G9PTw6idaPRlaiRw/GXkgvQjTtLilr9cq0jJIKTvRvrrnIKmUiDlabkLp5gwzI0QEZxbYgtewMM=
  on:
    tags: true
    repo: ACloudGuru/serverless-plugin-crypt
    branch: master
    node: '4.4'

notifications:
  slack:
    secure: PTbbYL/RP/L2MPOE/ndL0db4KoLL+pExGhnM5HTVbfmhBBc9HTiZwsJfiwDjU02h7s7lK0um/dK4wWG1vmbceHKcr/FzdSIpQvGLgq/o318c1S42ESqkMMT0o0Kjwd3pxlpRpemfyeQMPmdLmS7ZZh0e6MlmX68p1n2nts5EtP+d6FDw9ffWpIx+di/D0RhaBu37ePMqnNSwxStbM/PV1Un0LKHdg12WJ0CyFX8vuECI83AqHdPl+k6FYjncTaC+Bna9+iaBPUpfZ2HEdicwTRYy2q5DSquVAEzlVgm7fUGXXOr4hYhjNDcgbvSmlNC13+AD3+Q6jGMTloY9dNUAXuGtBBFtdrwGhvKYkftuHzvMNEStmRDPGw5BH/Yl1BdUJI8jBfopASiYKnxaMeeM1iDNjCdPZOPveYjISsPTRWzIVWS2h8RPjZSmrEfD0wGN243h3Ndb05nk7kXtJOQuXPXLCFWuLNA4Smy8ksZHO42UuDNEo1H2S9ua3DvCi9B16J6gGQUbZE+6cBys+d6vcV47vDR2hXV2yZSP4gjX9J72uEX6GbINVDNpK2XDZY253mH2M1m7g4BMpO186eXsxms2eQfYY2dbRD+tIFkYZS9Q0+1YDhQ9egDDqvGUF62/sHNs/xq17uNqFxg6wxBJTAflBNmTnAWwa5fSJRUp0u8=